FROM neo4j:5.20

ENV NEO4J_AUTH=neo4j/pfa_recommendationservice

EXPOSE 7474 7687

##to build image run : docker build -t neo4j-recommendation-service .
##then to run container from image run : docker run -d --name neo4j-recommendation-service -p 7475:7474 -p 7688:7687 -v neo4j_recommendation_data:/data neo4j-recommendation-service
